version: 2
jobs:
  build: 
    working_directory: ~/channable-assignment
    docker:
      - image: circleci/python:3.6.8
        environment:
            PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
            pipenv run python python test_main.py -v
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
